---
admin_samba_pw: '{{ vault_admin_samba_pw }}'
admin_un: guardians5

samba_server_string: 'Ansible Lab File Server'
samba_workgroup: SNIPER5
samba_users:
- name: '{{ admin_un }}'
  password: '{{ admin_samba_pw }}'
samba_shares_root: /srv/samba
samba_shares:
- name: Sniper5Repo
  comment: 'Only accessible to {{ admin_un }}'
  valid_users: '{{ admin_un }}'
  write_list: '{{ admin_un }}'
  group: '{{ admin_un }}'
  browseable: 'yes'